[project]
name = "nnmd"
version = "0.0.0.dev0"
description = "ML extension with PyTorch C++ (Libtorch) and Python bindings"
readme = "README.md"
keywords = ["python", "pytorch", "libtorch", "pybind11"]
authors = [
    {name = "Andrey Budnikov"}
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: GPU :: NVIDIA CUDA",
    "Programming Language :: Python :: 3",
    "Programming Language :: C++"
]

[project.urls]
Homepage = "https://github.com/ded-otshelnik/nnmd"
Repository = "https://github.com/ded-otshelnik/nnmd.git"

[project.optional-dependencies]
test = [
    "pytest"
]

[build-system]
# (!) torch must be compiled first
# for compatibility with extension
requires = ["setuptools",
            "wheel",
            "ninja",
            "cmake>=3.11",
            # dependencies from torch
            # must be added
            # if "pip install ." are used
            # for pyproject.toml-based project
            "typing_extensions",
            "sympy",
            "numpy"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [""]
exclude = ["test/"]

[tool.pytest.ini_options]
testpaths = "tests"  # directory containing your tests
norecursedirs = [
    ".vscode",
    "__pycache__"
]
# Warnings that should be ignored
filterwarnings = [
    "ignore::DeprecationWarning"
]
# custom markers that can be used using pytest.mark
markers = [
    "slow: lower-importance tests that take an excessive amount of time",
]