[project]
name = "nnmd"
version = "0.1.0"
description = "ML extension with PyTorch C++ (Libtorch) and Python bindings"
readme = "README.md"
keywords = ["python", "pytorch", "libtorch", "pybind11"]
authors = [
    {name = "Andrey Budnikov"}
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: GPU :: NVIDIA CUDA :: 12 :: 12.1",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: C++",
    "Programming Language :: Python :: Implementation :: CPython"
]

[project.urls]
Homepage = "https://github.com/ded-otshelnik/nnmd"
Repository = "https://github.com/ded-otshelnik/nnmd.git"

[project.optional-dependencies]
test = [
    "pytest"
]

[build-system]
# (!) torch must be compiled first for compatibility with extension
# but it mustn't be mentioned in 'requires'
# because pip will try to download torch from web resources 
# what will break extentions and their compatibility 
requires = ["setuptools==69.5.1",
            "wheel",
            "ninja",
            "cmake>=3.11",
            # dependencies from torch
            # must be added
            # if "pip install ." are used
            # for pyproject.toml-based project
            "typing_extensions",
            "sympy",
            "numpy"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [""]
exclude = ["test/"]

[tool.pytest.ini_options]
# directory containing your tests
testpaths = "tests"  
norecursedirs = [
    ".vscode",
    "__pycache__"
]
# warnings that should be ignored
filterwarnings = [
    "ignore::DeprecationWarning"
]
# custom markers that can be used using pytest.mark
markers = [
    "slow: lower-importance tests that take an excessive amount of time",
]