atomic_data:
  reference_data: input/lennard_jones_trimer.traj
  symmetry_functions_set: input/symm_lj.yaml

use_cuda: True

neural_network:
  atom_species: ['H']
  hidden_sizes: [[25, 25]]
  epochs: 500
  batch_size: 100
  learning_rate: 0.1
  l2_regularization: 0.0
  e_loss_coeff: 1.0
  f_loss_coeff: 0.1
  optimizer: 'adam'
  load_models: True
  path: 'models_trimer'
  train: True
  save: True
