atomic_data:
  reference_data: input/Li_crystal_27.traj
  symmetry_functions_set: input/symm_li_27.json

use_cuda: true

neural_network:
  atom_species: ['Li']
  hidden_sizes: [[32, 32]]
  epochs: 100
  batch_size: 500
  learning_rate: 0.001
  l2_regularization: 0.0001
  mu: 30.0
  load_models: False
  path: 'models'
  train: True
  save: True