atomic_data:
  reference_data: input/Li_crystal_27.traj
  symmetry_functions_set: input/symm_li_27.json

use_cuda: True

neural_network:
  atom_species: ['Li']
  hidden_sizes: [[64, 64]]
  epochs: 200
  batch_size: 500
  optimizer: 'adamw'
  learning_rate: 0.1
  l2_regularization: 0.0001
  e_loss_coeff: 1.0
  f_loss_coeff: 0.01
  load_models: True
  path: 'models_adamw'
  train: True
  save: True
