atomic_data:
  reference_data: input/cu111.txt
  symmetry_functions_set: input/symm_cu111.json

use_cuda: True

neural_network:
  atom_species: ['Cu']
  hidden_sizes: [[256, 64]]
  epochs: 400
  batch_size: 6
  optimizer: 'adamw'
  learning_rate: 0.1
  l2_regularization: 0.0
  e_loss_coeff: 1.0
  f_loss_coeff: 0.01
  load_models: True
  path: 'models_adamw'
  train: True
  save: True
